# This is example to learn python and scipy

In [1]:
import numpy as np

# Array

In [2]:
a = np.array([1,4,5,8], float)

In [3]:
print a

[ 1.  4.  5.  8.]


In [4]:
type(a)

numpy.ndarray

When used with an array, the len function returns the length of the first axis:

In [5]:
b = len(a)

In [6]:
print b

4


In [7]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
b = len(a)
print b

2


concatenate

If an array has more than one dimension, it is possible to specify the axis along which multiple
arrays are concatenated. By default (without specifying the axis), NumPy concatenates along
the first dimension:

In [9]:
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7,8]], float) 
c = np.concatenate((a,b))
print c

[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]]


In [10]:
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7,8]], float) 
c = np.concatenate((a,b), axis=0)
print c

[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]]


In [11]:
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7,8]], float) 
c = np.concatenate((a,b), axis=1)
print c

[[ 1.  2.  5.  6.]
 [ 3.  4.  7.  8.]]


broadcasted

In [12]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)
print a
print b
c = a+b
print c

[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]]
[-1.  3.]
[[ 0.  5.]
 [ 2.  7.]
 [ 4.  9.]]


In [13]:
a = np.array([-1., 3.], float)
print 'a'
print a
b = a[np.newaxis, :]
print 'b'
print b
print b.shape

a
[-1.  3.]
b
[[-1.  3.]]
(1, 2)


In [14]:
a = np.array([-1., 3.], float)
print 'a'
print a
b = a[:, np.newaxis]
print 'b'
print b
print b.shape

a
[-1.  3.]
b
[[-1.]
 [ 3.]]
(2, 1)


# Basic array operations

In [20]:
a = np.array([2,3,4])
b = a.argmin()
print b

0


In [21]:
a = np.array([2, 1, 9], float)
b = a.argmin()
print b

1


In [24]:
a = np.array([[1, 2], [3, -1], [3, 5]], float)
print 'a'
print a
b = a.sum(axis=0)
print 'b'
print b
print b.shape

a
[[ 1.  2.]
 [ 3. -1.]
 [ 3.  5.]]
b
[ 7.  6.]
(2,)


In [25]:
a = np.array([[1, 2], [3, -1], [3, 5]], float)
print 'a'
print a
b = a.sum(axis=1)
print 'b'
print b
print b.shape

a
[[ 1.  2.]
 [ 3. -1.]
 [ 3.  5.]]
b
[ 3.  2.  8.]
(3,)


In [26]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
for x in a:
    print x

[ 1.  2.]
[ 3.  4.]
[ 5.  6.]


In [28]:
a = np.array([[0, 1, 6], [2, 3, 7]], float)
print 'a'
print a
b = np.array([0, 0, 1], int)
print 'b'
print b
c = a.take(b, axis=0)
print 'c'
print c


a
[[ 0.  1.  6.]
 [ 2.  3.  7.]]
b
[0 0 1]
c
[[ 0.  1.  6.]
 [ 0.  1.  6.]
 [ 2.  3.  7.]]


In [29]:
a = np.array([[0, 1, 6], [2, 3, 7]], float)
print 'a'
print a
b = np.array([0, 0, 1], int)
print 'b'
print b
c = a.take(b, axis=1)
print 'c'
print c

a
[[ 0.  1.  6.]
 [ 2.  3.  7.]]
b
[0 0 1]
c
[[ 0.  0.  1.]
 [ 2.  2.  3.]]


Vector and matrix mathematics

In [30]:
a = np.array([1, 2, 3], float)
b = np.array([0, 1, 1], float)
c = np.dot(a, b)
print c

5.0


In [34]:
a = np.array([[0, 1], [2, 3]], float)
b = np.array([2, 3], float)
c = np.array([[1, 1], [4, 0]], float)
print 'a'
print a
print 'b'
print b
print 'c'
print c
d = np.dot(b, a)
print 'd'
print d

a
[[ 0.  1.]
 [ 2.  3.]]
b
[ 2.  3.]
c
[[ 1.  1.]
 [ 4.  0.]]
d
[  6.  11.]


last code: we assue that b is 1x2 and a is 2x2

In [35]:
a = np.array([[0, 1], [2, 3]], float)
b = np.array([2, 3], float)
c = np.array([[1, 1], [4, 0]], float)
print 'a'
print a
print 'b'
print b
print 'c'
print c
d = np.dot(a, b)
print 'd'
print d

a
[[ 0.  1.]
 [ 2.  3.]]
b
[ 2.  3.]
c
[[ 1.  1.]
 [ 4.  0.]]
d
[  3.  13.]


last code: we assue that a is 2x2 and b is 2x1

In [36]:
a = np.array([[0, 1, 3], [2, 3, 4]], float)
b = np.array([2, 3], float)
c = np.array([[1, 1], [4, 0]], float)
print 'a'
print a
print 'b'
print b
print 'c'
print c
d = np.dot(b, a)
print 'd'
print d

a
[[ 0.  1.  3.]
 [ 2.  3.  4.]]
b
[ 2.  3.]
c
[[ 1.  1.]
 [ 4.  0.]]
d
[  6.  11.  18.]


last code: we assue that b is 1x2 and a is 2x3

In [37]:
a = np.array([[0, 1, 3], [2, 3, 4]], float)
b = np.array([2, 3], float)
c = np.array([[1, 1], [4, 0]], float)
print 'a'
print a
print 'b'
print b
print 'c'
print c
d = np.dot(a, b)
print 'd'
print d

a
[[ 0.  1.  3.]
 [ 2.  3.  4.]]
b
[ 2.  3.]
c
[[ 1.  1.]
 [ 4.  0.]]


ValueError: shapes (2,3) and (2,) not aligned: 3 (dim 1) != 2 (dim 0)

last code: we assue that a is 2x3 
b can be any chance of 1x2 or 2x1, which both can not fit the dimension

In [39]:
a = np.array([[0, 1], [2, 3]], float)
c = np.array([[1, 1], [4, 0]], float)
d =  np.dot(a, c)
print d
d = np.dot(c, a)
print d

[[  4.   0.]
 [ 14.   2.]]
[[ 2.  4.]
 [ 0.  4.]]


last code: perform just like matlab

# Random numbers

NumPy uses a particular algorithm called the **Mersenne Twister** to generate
pseudorandom numbers

The random number seed can be set:

In [40]:
np.random.seed(293423)

The seed is an integer value. Any program that starts with the same seed will generate exactly
the same sequence of random numbers each time it is run. This can be useful for debugging
purposes, but one does not need to specify the seed and in fact, when we perform multiple
runs of the same simulation to be averaged together, we want each such trial to have a
different sequence of random numbers. If this command is not run, NumPy automatically
selects a random seed (based on the time) that is different every time a program is run.

An array of random numbers in the half-open interval [0.0, 1.0) can be generated:

In [41]:
 np.random.rand(5)

array([ 0.33677247,  0.52693437,  0.79529578,  0.78867702,  0.02147624])

The rand function can be used to generate two-dimensional random arrays, or the resize
function could be employed here:

In [42]:
np.random.rand(2,3)
np.random.rand(6).reshape((2,3))

array([[ 0.90239653,  0.8385685 ,  0.02638565],
       [ 0.33681448,  0.46480928,  0.61686496]])

To generate a single random number in [0.0, 1.0),

In [43]:
 np.random.random()

0.43767262538051455

To generate random integers in the range [min, max) use randint(min, max):

In [44]:
np.random.randint(5, 10)

5

In each of these examples, we drew random numbers form a uniform distribution. NumPy also includes generators for many other distributions, including the Beta, binomial, chi-square, Dirichlet, exponential, F, Gamma, geometric, Gumbel, hypergeometric, Laplace, logistic, lognormal, logarithmic, multinomial, multivariate, negative binomial, noncentral chi-square, noncentral F, normal, Pareto, Poisson, power, Rayleigh, Cauchy, student's t, triangular, von Mises, Wald, Weibull, and Zipf distributions. Here we only give examples for two of these.

To draw from the discrete Poisson distribution with $\lambda=6$

In [45]:
np.random.poisson(6.0)

4

To draw from a continuous normal (Gaussian) distribution with mean $\mu=1.5$ and standard deviation $\sigma=4$:

In [46]:
np.random.normal(1.5, 4.0)

-1.5224080889736675

To draw from a standard normal distribution $(\mu=0,\sigma=1)$, omit the arguments:

In [47]:
np.random.normal()

0.957100788846741

To draw multiple values, use the optional size argument:

In [48]:
np.random.normal(size=5)

array([-1.01092541,  0.58092445,  1.122653  , -0.1252049 ,  0.57716007])

In [49]:
np.random.normal(1.5, 4.0, size=5)

array([-5.44942258, -0.65215895, -0.91855863,  3.76901165, -1.24340282])

The random module can also be used to randomly shuffle the order of items in a list. This is
sometimes useful if we want to sort a list in random order:

In [50]:
l = range(10)