# This is example to learn python and scipy

In [1]:
import numpy as np

# Array

In [2]:
a = np.array([1,4,5,8], float)

In [3]:
print a

[ 1.  4.  5.  8.]


In [4]:
type(a)

numpy.ndarray

When used with an array, the len function returns the length of the first axis:

In [5]:
b = len(a)

In [6]:
print b

4


In [7]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
b = len(a)
print b

2


concatenate

If an array has more than one dimension, it is possible to specify the axis along which multiple
arrays are concatenated. By default (without specifying the axis), NumPy concatenates along
the first dimension:

In [9]:
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7,8]], float) 
c = np.concatenate((a,b))
print c

[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]]


In [10]:
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7,8]], float) 
c = np.concatenate((a,b), axis=0)
print c

[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]]


In [11]:
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7,8]], float) 
c = np.concatenate((a,b), axis=1)
print c

[[ 1.  2.  5.  6.]
 [ 3.  4.  7.  8.]]


broadcasted

In [12]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)
print a
print b
c = a+b
print c

[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]]
[-1.  3.]
[[ 0.  5.]
 [ 2.  7.]
 [ 4.  9.]]


In [13]:
a = np.array([-1., 3.], float)
print 'a'
print a
b = a[np.newaxis, :]
print 'b'
print b
print b.shape

a
[-1.  3.]
b
[[-1.  3.]]
(1, 2)


In [14]:
a = np.array([-1., 3.], float)
print 'a'
print a
b = a[:, np.newaxis]
print 'b'
print b
print b.shape

a
[-1.  3.]
b
[[-1.]
 [ 3.]]
(2, 1)


# Basic array operations

In [20]:
a = np.array([2,3,4])
b = a.argmin()
print b

0


In [21]:
a = np.array([2, 1, 9], float)
b = a.argmin()
print b

1


In [24]:
a = np.array([[1, 2], [3, -1], [3, 5]], float)
print 'a'
print a
b = a.sum(axis=0)
print 'b'
print b
print b.shape

a
[[ 1.  2.]
 [ 3. -1.]
 [ 3.  5.]]
b
[ 7.  6.]
(2,)


In [25]:
a = np.array([[1, 2], [3, -1], [3, 5]], float)
print 'a'
print a
b = a.sum(axis=1)
print 'b'
print b
print b.shape

a
[[ 1.  2.]
 [ 3. -1.]
 [ 3.  5.]]
b
[ 3.  2.  8.]
(3,)


In [26]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
for x in a:
    print x

[ 1.  2.]
[ 3.  4.]
[ 5.  6.]


In [28]:
a = np.array([[0, 1, 6], [2, 3, 7]], float)
print 'a'
print a
b = np.array([0, 0, 1], int)
print 'b'
print b
c = a.take(b, axis=0)
print 'c'
print c


a
[[ 0.  1.  6.]
 [ 2.  3.  7.]]
b
[0 0 1]
c
[[ 0.  1.  6.]
 [ 0.  1.  6.]
 [ 2.  3.  7.]]


In [29]:
a = np.array([[0, 1, 6], [2, 3, 7]], float)
print 'a'
print a
b = np.array([0, 0, 1], int)
print 'b'
print b
c = a.take(b, axis=1)
print 'c'
print c

a
[[ 0.  1.  6.]
 [ 2.  3.  7.]]
b
[0 0 1]
c
[[ 0.  0.  1.]
 [ 2.  2.  3.]]


Vector and matrix mathematics

In [30]:
a = np.array([1, 2, 3], float)
b = np.array([0, 1, 1], float)
c = np.dot(a, b)
print c

5.0
